### PR TITLE
Change .travis.yml to use rebar3

### PR DESCRIPTION
**Pull request by edgurgel**
This should be enough to make Travis CI use rebar3

### CODE REVIEW

**Comment by edgurgel** [comment]
For some reason R15 and R15B1 are failing to fetch the dependencies:

```
===> Verifying dependencies...
===> Fetching ssl_verify_hostname ({pkg,<<"ssl_verify_hostname">>,
                                           <<"1.0.5">>})
===> Failed to fetch and copy dep: {pkg,<<"ssl_verify_hostname">>,<<"1.0.5">>}
```

**Comment by benoitc** [comment]
imo we should just switch to R18 for 2.0 at least R17. thoughts?

**Comment by edgurgel** [comment]
@benoitc, seems legit 17+ for 2.0. Any plans to release a working branch? I was thinking on writing unit tests for most modules but I don't want to start when the code may change drastically :D

@tsloughter, is rebar3 supposed to support somehow R15? For some reason it's breaking on Travis during download. 

I'm ok to drop support to R15 if @benoitc agrees.

**Comment by tsloughter** [comment]
Actually yes, we test against R15B03-1. Technically we would be removing it now that 18 is out (we plan to only support current OTP and 2 previous majors), but I don't see the point right now.

**Comment by benoitc** [comment]
@edgurgel I will merge tomorrow current work from the branch [hackney_socks](https://github.com/benoitc/hackney/tree/hackney/hackney_socks) and latest master tomorrow. In the process I will probably make some changes less drastic.

**Comment by edgurgel** [comment]
I just noticed that the hackney integration tests are not running with rebar3...

**Comment by benoitc** [comment]
@edgurgel can you rebase against the latest version of hackney to check the tests are running?

**Comment by benoitc** [comment]
fixed in latest master. Thanks!

**Comment by edgurgel** [comment]
Too fast :)

**Comment by edgurgel** [comment]
I wonder what's the best way to run the integration tests using rebar3 cause they are not running :/ We went from 159 to 138 tests after this change

**Comment by jlouis** [comment]
create an empty `hackney_integration.erl` module :) rebar3 only runs a test module if it corresponds to a real module IIRC.

**Comment by edgurgel** [comment]
Ok! Apparently running `./rebar3 eunit --dir="test"` does the trick

**Pull request closed without merging**
