### PR TITLE
Allow merging of SSL opts

### PR DESCRIPTION
**Pull request by spydon**
Related to #654
Since it isn't currently possible to merge your custom ssl opts with the default ones it could be a first step to expose the default ones so that the merging can be done client side.

### CODE REVIEW

**Comment by benoitc** [comment]
wouldn't exposing the `partial_chain` function just be enough?

**Comment by spydon** [comment]
It would work, but then the client still needs to duplicate the full list of default otps when setting custom ones.

**Comment by spydon** [comment]
What do you think @benoitc? 
And also, do you know why the checks are failing on some of the erlang versions?

**Comment by benoitc** [comment]
> What do you think @benoitc?
> And also, do you know why the checks are failing on some of the erlang versions?

don't worry about the syntax issue. It's one of these usual  bugs of Travis...  The issue with that change is that some people will still wnt maybe to use some other settings imo. Maybe instead of replacing ssl options we could merge them or provide a way to merge defaults and the one in options ? this could be done there: https://github.com/benoitc/hackney/blob/master/src/hackney_connection.erl#L125 

Thoughts?

**Comment by spydon** [comment]
Yeah, that would be a better solution. But that would either be a breaking change, or to introduce a new method there?
With the current change it will work the same as it does currently for those who want to use other settings, since the merging of the settings will need to be done client side and you would have to consciously call the new function to get the default opts.

**Comment by spydon** [comment]
@benoitc would something like this be better maybe?

**Comment by spydon** [comment]
Sorry to be a bother, have you had any time to look at this yet @benoitc? :)

**Comment by benoitc** [comment]
sorry for the late answer. That would probably work. I am doing  a release today possibly including it :)

**Comment by spydon** [comment]
@benoitc is the plan to get this out on the 14th of November like it says on the milestone date? :)

**Comment by spydon** [comment]
@benoitc any plan for when the new release will be released?

**Comment by benoitc** [comment]
@spydon next release will happen next week on thursday.  this feature should be part of it normally.

**Comment by benoitc** [comment]
> @spydon next release will happen next week on thursday. this feature should be part of it normally.

that has been slightly delayed. It will happen this week, coming with a new documentation website.

**Comment by spydon** [comment]
Any updates on the release? :)
We are seeing several teams having this problem now.

**Comment by benoitc** [comment]
> Any updates on the release? :)
> We are seeing several teams having this problem now.

i will merge a minor release with it later today

**Pull request merged**
