### PR TITLE
Use destination as pool reference for hackney_http_connect transport

### PR DESCRIPTION
**Pull request by ennocramer**
When the HTTP CONNECT method is used for proxied requests, sockets are
bound to the destination host and cannot be reused for requests to
other hosts.  The sockets should therefore be index based on the
destination host, not the proxy host.

This setup is still broken when multiple proxies, or proxied and non-proxied connections, are used at the same time, as connections over either proxy are considered identical.

This change should improve the situation for issues #355 and #566

### CODE REVIEW

**Comment by ennocramer** [comment]
I made a mistake in my tests. This PR does not work as it is supposed to. Please do not merge yet.

**Comment by ennocramer** [comment]
Apologies for the delay with fixing this PR.

I had initially believed it would be easiest to retain the shape of the pool checkin reference and simply swap out the proxy information with the final host. I did not realize that various other functions require access to the proxy transport value and would require passing additional arguments. I now believe the correct fix is to include both the proxy and final host in the checkin reference. This also means that the limitation in my first comment about connections to the same host with different proxy settings no longer applies.

**Comment by benoitc** [comment]
@ennocramer appologies for the delay to answer, the pr shows the right path anyway. I will take it around. IMO proxies could be handled as an independant resource you link o when making a connection either as a process but lso supervision. I need to think a little bit about it.

**Comment by benoitc** [comment]
it's now fixed in master. Thanks for your patch it was a good basis.

**Pull request closed without merging**
