### PR TITLE
fix return value of del_from_queue

### PR DESCRIPTION
**Pull request by jimdigriz**
Fixes https://github.com/benoitc/hackney/issues/452 ....probably.

### CODE REVIEW

**Comment by byronpc** [comment]
@jimdigriz I've been observing, the checkout_cancel in general. And it seems this cast gets stuck and causes a deadlock in the pool. 

```
Message queue:[{'$gen_cast',{checkout_cancel,{"gcm-http.googleapis.com",443,hackney_ssl},#Ref<0.0.7340050.2138>}},{'$gen_
cast',{checkout_cancel,{"gcm-http.googleapis.com",443,hackney_ssl},#Ref<0.0.7340050.2114>}},{'$gen_cast',{checkout_cancel
,{"gcm-http.googleapis.com",443,hackney_ssl},#Ref<0.0.7340050.2147>}},{'$gen_cast',{checkout_cancel,{"gcm-http.googleapis
.com",443,hackney_ssl},#Ref<0.0.7340050.2149>}},{'$gen_cast',{checkout_cancel,{"gcm-http.googleapis.com",443,hackney_ssl}
,#Ref<0.0.7340050.2151>}},{'$gen_cast',{checkout_cancel,{"gcm-http.googleapis.com",443,hackney_ssl},#Ref<0.0.7340050.2156
>}},{'$gen_cast',{checkout_cancel,{"gcm-http.googleapis.com",443,hackney_ssl},#Ref<0.0.7340050.2127>}},{'$gen_cast',{chec
kout_cancel,{"gcm-http.googleapis.com",443,hackney_ssl},#Ref<0.0.7340050.2136>}},{'$gen_cast',{checkout_cancel,{"gcm-http
.googleapis.com",443,hackney_ssl},#Ref<0.0.11272197.128945>}},{'$gen_call',{<0.25658.2592>,#Ref<0.0.18350081.17329>},{che
ckout,{"gcm-http.googleapis.com",443,hackney_ssl},<0.25658.2592>,#Ref<0.0.18350081.17315>}},{'$gen_call',{<0.10419.2592>,
#Ref<0.0.18350081.17330>},{checkout,{"gcm-http.googleapis.com",443,hackney_ssl},<0.10419.2592>,#Ref<0.0.18350081.17317>}}
,{'$gen_call',{<0.3498.2409>,#Ref<0.0.18350081.17338>},
```

As you notice there's a couple of checkout_cancel messages in the queue causing all other succeeding calls to hackney to fail for a short time.

**Comment by jimdigriz** [comment]
You say 'fail for a short time', so I am going on the assumption that that message is not being handled is `hackney_pool` is busy elsewhere; its a gen_server, and nothing exciting is going on here.

This behavior is expected if the upstream HTTP server is taking its time to respond (longer than the set `connect_timeout`) which is the way the state machine gets to this point.

The patch does not fix this, and it is impossible to fix this if you want to enforce a limit on `pool_size` as the problem is the upstream server timing out or at least being very slow.  What the `checkout_cancel` patch fixed was that hackney would deadlock and not recover from this situation.

If your environment is where timeouts/slow-responses are the norm *and* you want to limit the `pool_size` there is nothing that you can do here...  Maybe you can lessen the effect by setting `connect_timeout` to ~3x the RTT to the upstream server you are contacting?

**Comment by silviucpp** [comment]
@jimdigriz we are experience this issue 100 % when we increase the pool size. For example with a pool size of 100 connections we didn't experienced the problem for more than 1 day, with 200 connections we experienced the problem after 8 hours and with 500 connections it's going crazy in less than 2 hours (can be 100 % replicated)

So somehow the pool size have an important role in this problem

Silviu

**Comment by jimdigriz** [comment]
....because your upstream HTTP server you are querying, which regularly struggles with <100 connections, is now completely swamped with 5x the load.  The patch fixes it so that once the upstream HTTP server recovers, hackney *also* recovers.

I am making a really poor job of communicating here.  All I can recommend is you plot a histogram (via a packet capture and not from inside erlang) showing the HTTP response times of your HTTP server.  Maybe you have access to the upstream server and can make the measurements from there...if you can also look at the TCP listen queue drops for hints.

**Comment by silviucpp** [comment]
Hello @jimdigriz,

The server we are query is Google GCM service (gcm-http.googleapis.com). Idea is that we started to face this problems after we upgraded hackney from 1.4.x to last stable. Our traffic didn't increased in number of pushes delivered for this reason we suspect something with hackney

Anyway probably we need to enable hackney stats and to see the response times 

Thanks,
Silviu

**Comment by jimdigriz** [comment]
As it is Google, rather than overloading, it could be throttling which would have the same effect.

**Comment by sntran** [comment]
I cannot produce a standalone repo, but I do have the same issue when working with Google Maps API. The library is at https://github.com/sntran/ex_maps, when running tests, work fine with `hackney@1.9`, but generates the exception in 1 out of 40+ tests when using `hackney@1.10.1`

Last message: `{:"$gen_cast", {:checkout_cancel, {'maps.googleapis.com', 443, :hackney_ssl}, #Reference<0.1841845360.644349953.119089>}}`

**Pull request merged**
