### PR TITLE
sockname and peername access from hackney module

### PR DESCRIPTION
**Pull request by c-bik**
Hi @benoitc,

First off great job 👍. This application has more useful features than most other http clients out there (including `httpc`).

Here is a small PR with some helper APIs to access IP and Port from `ConnRef` returned by `hackney:connect/1,2,3,4` and also a few cosmetic changes for README. These will help in another project (I am also contributing) where hackney is considered to be used.

Hope you find this PR useful as well.

Thanks!

### CODE REVIEW

**Comment by c-bik** [comment]
Please also feel free to point out if anything in this PR can be improved.

**Comment by benoitc** [comment]
looking at the PR sorry for the delay, somehow github notifications are broken :/

**Comment by benoitc** [comment]
changes to the source code are good. However the changes to the readme file should happen in the overview.edoc file since the README is generated from it. Do you want to do the changes, I could take care of it if not. Just le t me know :)

**Comment by c-bik** [comment]
@benoitc Sorry to miss that overview.edoc bit! I would like to give that a shot over the weekend, if you can wait that long. Otherwise please feel free.

Thanks for your time to this PR 👍

**Comment by c-bik** [comment]
Gave it a try, however, `rebar3 edoc` is producing a lot of changes all over `md`! Wasn't sure about them so didn't push!

Please have a look!

_Thanked myself too, hope you won't mind_ 😉

**Comment by benoitc** [comment]
i will check tomorrow. Sorry for the delay!

**Pull request merged**
