### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by deadtrickster**
use `./rebar3 shell` command to `run a shell with project apps and deps in path.` (old -pa stuff doesn't work anymore)

### CODE REVIEW

**Comment by benoitc** [comment]
Thanks for the patch. Hoever the change should be made in the overview file instead. The readme is generated from it. Can you do the changes?

Also I wonder if we shouldn't add a note for zsh users (on which the script is buggy) yto use the command line `erl -pa _build/default/*/ebin` instead. Thoughts?

**Comment by deadtrickster** [comment]
I just tried on zsh 5.0.5 - works perfectly!

**Comment by benoitc** [comment]
hrm will retry on my mac. when you exit here the text is scrambled

**Comment by benoitc** [comment]
@deadtrickster about the issue: 
https://github.com/rebar/rebar3/issues/644#issuecomment-140117818

What about documenting both? Can you do that change?

**Comment by deadtrickster** [comment]
How about these lines: "It is suggested that you install rebar3 user-wide as described here http://blog.erlware.org/rebar3-features-part-1-local-install-and-upgrade/. This fixes zsh (and maybe other shells) escript-related bugs. Also this should speed things up."

**Comment by benoitc** [comment]
:+1:

**Comment by deadtrickster** [comment]
done

**Comment by benoitc** [comment]
Thanks!

**Pull request merged**
