### PR TITLE
Add test for async HEAD request

### PR DESCRIPTION
**Pull request by lexmag**

### CODE REVIEW

**Comment by benoitc** [comment]
I assume that SetupData ws here for  reason. @edgurgel  any idea?

**Comment by edgurgel** [comment]
Not really. I thought it was necessary for the eunit test cases to receive a function of arity 1, but apparently it's not :)

**Comment by benoitc** [comment]
ok just merged the change then. Thanks!

**Comment by edgurgel** [comment]
:+1:

**Comment by lexmag** [comment]
Thanks.

**Pull request merged**
