### PR TITLE
Add connect_timeout pool test

### PR DESCRIPTION
**Pull request by fishcakez**
Hackney pool leaks connections on connect timeout added in #402. The pool leaks the connections until the timed out process closes. Note that prior to that PR this test would also fail, or rather timeout, because it would block for an unbounded amount of time.

### CODE REVIEW

**Comment by mkarnebeek** [comment]
Looks like its related to #420

**Comment by mkarnebeek** [comment]
Confirmed. Setting https://github.com/benoitc/hackney/pull/402/files#diff-386dad9b4fb4d24c07d595eaf7c2bb00R68 to `infinity` solves #420 for me.

**Comment by benoitc** [comment]
thanks for the test, i will have a look on how to correctly fix it.

**Comment by Hinidu** [comment]
Hello! Is there a way to disable pool while this issue is not resolved? I'm using `hackney` with [ex_aws](https://github.com/CargoSense/ex_aws).

**Comment by mkarnebeek** [comment]
I'm still encountering this issue. Disabling pooling is not a option for us. Any progress?

**Comment by jimdigriz** [comment]
Unit test breaks `hackney_integration_tests.erl` as it [clobbers the application environment](https://github.com/benoitc/hackney/pull/440#issuecomment-337053175).

Solution is to use [`hackney_pool:start_pool(..., [{pool_size,1}])` instead](https://github.com/jimdigriz/hackney/commit/8032e2b0eaf3880fb436b0d09f23beced9690471).

**Comment by benoitc** [comment]
available in master. Thanks @fishcakez @jimdigriz for the patches

**Pull request closed without merging**
