### PR TITLE
Link checkout process to fix dangling aborted request

### PR DESCRIPTION
**Pull request by ronaldwind**

### CODE REVIEW

**Comment by devality** [comment]
This fix solved our problem. Could someone merge it please?

**Comment by benoitc** [comment]
i  am working an alternative implementation. I will see if it can goes in a minor release in between.

**Comment by benoitc** [comment]
also do you have any test reproducing the issue?

**Comment by ronaldwind** [comment]
> also do you have any test reproducing the issue?

No, sorry, the only thing I've tried is the snippet of https://github.com/benoitc/hackney/issues/675.

**Pull request merged**
