### PR TITLE
Follow HTTP 308 redirects

### LINKED ISSUE #635: Follow HTTP 308 redirects
Hi,

Hackney specifies the following status codes as redirects follow with follow_redirect: https://github.com/benoitc/hackney/blob/6bd1f46d98757246cd0896624ff12587451ed122/src/hackney.erl#L735

I think [HTTP 308](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308) should be included too. For instance, pinterest returns HTTP 308 when accessing the non-www domain.

### PR DESCRIPTION
**Pull request by AntoineAugusti**
Fixes #635 

I'm not sure if I need to make other changes. Did a few searches on the codebase and did not find obvious things to change. Let me know if I missed something.

### CODE REVIEW

**Comment by AntoineAugusti** [comment]
@benoitc Wondering if we can do this regarding this PR!

**Comment by AntoineAugusti** [comment]
Hi @benoitc, we would love to get this change merge as we require it upstream ❤️

**Comment by fchabouis** [comment]
Hi,
I would be glad too if this was merged!
Thanks :)

**Comment by benoitc** [comment]
there is a coming release tomorrow. This will be part of it.

**Pull request merged**
