### PR TITLE
test erlang 21

### PR DESCRIPTION
**Pull request by getong**
The erlang-certifi needs parse_trans 3.3.0 for dep, I also make a pr to it, see certifi/erlang-certifi#31.
If that pr merged and a new tag is made, I will modify this pr.

### CODE REVIEW

**Comment by getong** [comment]
@benoitc 
Is there anything wrong and anything needs to be improved?

**Comment by benoitc** [comment]
I have ported your patch in master via different sub commits. Thanks for it anyway!

**Comment by getong** [comment]
I think you can cherry-pick my commit, it is not a very good practice.

**Comment by benoitc** [comment]
@getong sorry, cherry-picking was not enough in this case since changes were not much isolated . Rather than asking you to do the change 1 month after I did the work. I have been lazy about commit messages though. It's now fixed. See  29910e54be8e8d57b31d0d2dae7e186165771aef & 4a828f9e56bd0afd5b70c35bb140ffd0c6579f9a

**Pull request closed without merging**
