### PR TITLE
hackney_url:normalize function should actually use the function in the argument instead of pathencode()

### PR DESCRIPTION
**Pull request by sikanhe**
from https://github.com/benoitc/hackney/issues/272

### CODE REVIEW

**Comment by sikanhe** [comment]
Also realized that we had a typo, encodepath/1 should be pathencode/1, fixed it in the latest commits

**Comment by benoitc** [comment]
thanks!

**Comment by sikanhe** [comment]
Is it possible to get a version bump on hex.pm  for this feature ?

**Comment by benoitc** [comment]
i tought i did :/ will do later tonight, sorry for that.

**Comment by sikanhe** [comment]
it's all good, I am asking you to do me favors :) so you don't have to apologize for anything

**Comment by benoitc** [comment]
@sikanhe 1.6.0 has been released. enjoy!

**Comment by sikanhe** [comment]
@benoitc awesome

**Pull request merged**
