### PR TITLE
don't try to encode to idna an full ascii name.

### LINKED ISSUE #557: "Codepoint 95 not allowed" -- too restrictive
```
1> application:ensure_all_started(hackney).
2> hackney:request(get, hackney_url:make_url("http://foo_bar", [], []), [], [], []).
** exception exit: {bad_label,{alabel,"The label \"foo_bar\"  is not a valid A-label: ulabel error={bad_label,\n                                                           {context,\n                                                            \"Codepoint 95 not allowed ('DISALLOWED') at posion 3 in \\\"foo_bar\\\"\"}}"}}
     in function  idna:alabel/1 (src/idna.erl, line 277)
     in call from idna:encode_1/2 (src/idna.erl, line 145)
     in call from hackney_url:normalize/2 (src/hackney_url.erl, line 99)
     in call from hackney:request/5 (src/hackney.erl, line 306)
```

Underscores are allowed in hostnames: https://stackoverflow.com/questions/2180465/can-domain-name-subdomains-have-an-underscore-in-it

Related to #534.

### PR DESCRIPTION
**Pull request by benoitc**
some local hostname contains an underscore or other things that are
tolerated by clients like curl. Do the same as curl then and just try to
encode the domain name if it contains some unicode characters.

fix #557

### CODE REVIEW

**Comment by rlipscombe** [comment]
Hmmm:

```
<0.83.0> 6> Url = hackney_url:make_url("http://moar_underscores", [], []).    
<<"http://moar_underscores">>
<0.83.0> 7> hackney:request(get, Url, [], [], []).                        
** exception exit: {bad_label,{alabel,"The label \"moar_underscores\"  is not a valid A-label: ulabel error={bad_label,\n                                                                    {context,\n                                                                     \"Codepoint 95 not allowed ('DISALLOWED') at posion 4 in \\\"moar_underscores\\\"\"}}"}}
     in function  idna:alabel/1 (src/idna.erl, line 277)
     in call from idna:encode_1/2 (src/idna.erl, line 145)
     in call from hackney_url:normalize/2 (src/hackney_url.erl, line 101)
     in call from hackney:request/5 (src/hackney.erl, line 306)
<0.89.0> 8> hackney_url:idnconvert_hostname("moar_underscores").          
"moar_underscores"
```

Note that `moar_underscores` isn't in DNS; this is all in-hackney text handling at this point.

**Comment by rlipscombe** [comment]
Looks like it's failing at https://github.com/benoitc/hackney/blob/master/src/hackney_url.erl#L99

**Comment by benoitc** [comment]
@rlipscombe that should work now

**Comment by rlipscombe** [comment]
```
2> Url = hackney_url:make_url("http://this_has_underscores", [], []).
<<"http://this_has_underscores">>
3> hackney:request(get, Url, [], [], []).                            
{ok,200,
    [{<<"Server">>,<<"nginx/1.10.3 (Ubuntu)">>},
     {<<"Date">>,<<"Mon, 25 Feb 2019 11:39:18 GMT">>},
     {<<"Content-Type">>,<<"text/html">>},
     {<<"Content-Length">>,<<"612">>},
     {<<"Last-Modified">>,<<"Sun, 17 Dec 2017 20:19:35 GMT">>},
     {<<"Connection">>,<<"keep-alive">>},
     {<<"ETag">>,<<"\"5a36d157-264\"">>},
     {<<"Accept-Ranges">>,<<"bytes">>}],
    #Ref<0.515037661.3568566273.257182>}
```

:+1:

**Pull request merged**
