### PR TITLE
ssl_closed fix

### PR DESCRIPTION
**Pull request by AlexanderKai**
Here is a few lines of code that can fix up issue #464 in my opinion.

### CODE REVIEW

**Comment by benoitc** [comment]
I willl test it later today but looks good so far. Thanks for the patch!

**Comment by stephenmoloney** [comment]
I tried to backport these changes to `1.10.1` but I am still running into the same error.
I can't upgrade to `1.11.0` as I keep running into the error on #447. I can reproduce the error in #447 and I'll post that over on that issue once i get the chance.

The local tests don't seem to output the error but building on travis does. 

`1.10.1` -> https://travis-ci.org/stephenmoloney/fastimage/builds/345600324

`1.10.1 with ssl_fix` -> https://travis-ci.org/stephenmoloney/fastimage/builds/345602341

**Comment by AlexanderKai** [comment]
@stephenmoloney 
That fix don't solves issue #447.

**Comment by critch** [comment]
While testing this for #479 I ran into what might be a worse situation. While not crashing out with the unexpected error message, it will not return the done message. So in effect, the download loop will fail to exit do to never receiving the done message.

**Comment by AlexanderKai** [comment]
@critch 
Can you send me test case for reproduce it?

**Comment by benoitc** [comment]
have a look in #482 as well, that should probably fix the error but let me know.

**Comment by benoitc** [comment]
i commited 91aadac9f929966087eef73fe09d1131441dd129 which should fix the issue.

**Pull request closed without merging**
